Repository Pinecone-aqua/receta, pull requests merged in 2023-05, with the labels that each got.

#140 tools store done
  client/public/Rectangle.png
  client/src/icons/SearchIcon.tsx
  client/src/pages/store.tsx
Labels: create

#158 151 dashboard searching
  admin/src/components/Navbar.tsx
  admin/src/components/recipe/CreateRecipe.tsx
  admin/src/components/recipe/DeleteRecipe.tsx
  admin/src/components/recipe/functions/mapping/InputMappingInCreate.tsx
  admin/src/components/recipe/functions/mapping/InputMappingInEdit.tsx
  admin/src/components/recipe/functions/recipePage/CategoriesMain.tsx
  admin/src/components/recipe/functions/recipePage/RecipeMain.tsx
  admin/src/components/recipe/functions/recipePage/ToolsMain.tsx
  admin/src/components/recipe/functions/tables/CategoriesTable.tsx
  admin/src/components/recipe/functions/tables/RecipeTable.tsx
  admin/src/components/recipe/functions/tables/RecipeTableRow.tsx
  admin/src/components/recipe/functions/tables/ToolsTable.tsx
  admin/src/components/tool/CreateTool.tsx
  admin/src/pages/Recipe.tsx
  client/src/pages/store.tsx
  client/tsconfig.json
  server/src/main.ts
Labels: create

#172 mobile menu finish
  client/src/component/Footer.tsx
  client/src/component/cocktail/Details.tsx
  client/src/component/main/Login.tsx
  client/src/component/main/Recommend.tsx
  client/src/component/main/menu/MenuItem.tsx
  client/src/component/main/menu/MenuToggle.tsx
  client/src/component/main/menu/Navigation.tsx
  client/src/pages/cocktail/[id].tsx
  client/src/pages/index.tsx
  client/src/styles/main/collection.scss
  client/src/styles/main/motion-menu.scss
  client/src/styles/main/parallax.scss
  client/src/styles/main/single.scss
Labels: changes, svlde

#187 dashbooard chart rendering fast af, usercontext uncommented
  admin/src/components/dashboard/AllData.tsx
  admin/src/components/dashboard/RecipeColGraphic.tsx
  admin/src/context/UserContext.tsx
  admin/src/pages/index.tsx
Labels: changes

#189 188 admin recipe editing bug
  admin/src/components/recipe/EditRecipe.tsx
  server/src/recipes/recipes.controller.ts
  server/src/recipes/recipes.service.ts
Labels: bug

#194 style changed in recipe table
  admin/src/components/recipe/functions/recipePage/CategoriesMain.tsx
  admin/src/components/recipe/functions/recipePage/RecipeMain.tsx
  admin/src/components/recipe/functions/recipePage/ToolsMain.tsx
  admin/src/components/recipe/functions/tables/RecipeTable.tsx
  admin/src/components/recipe/functions/tables/RecipeTableRow.tsx
  admin/src/components/recipe/functions/tables/recipePopups/DescPopover.tsx
  admin/src/components/recipe/functions/tables/recipePopups/HowToPopover.tsx
  admin/src/components/recipe/functions/tables/recipePopups/IngPopover.tsx
  admin/src/components/recipe/functions/tables/recipePopups/ToolsPopover.tsx
  client/package-lock.json
Labels: changes

#196 recipe updating done
  admin/src/components/recipe/EditRecipe.tsx
  server/src/recipes/recipes.service.ts
Labels: bug
